trigger:
  - develop

jobs:
  - job: Front
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: tpfinal-vars
    steps:
      - template: templates/_build-front.yml

      - task: PublishPipelineArtifact@1
        displayName: Publish dist artifact
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/dist
          artifact: front-dist
          publishLocation: pipeline
